### ISSUE TITLE
Data Together Semester 3 (2020)

### ISSUE THREAD

**Issue by Frijol** [datatogether/reading_datatogether#71]
In our [DT Annual Meeting](https://docs.google.com/document/d/1-uPPavAgzS0tp9seD4ekLVtAPp54mvkWbD0eK6jxK08/edit#) we made solid headway on the next reading group:

# Our 2020 Plan: “Polity: What is my civic role?”

What is the role of an individual in a system where we hold civic roles both in political and in digital contexts? What are the implications of one’s polity not aligning with one’s national or governmental state? 

  | Reading Group Topic Title | Themes (detailed) | Facilitator
-- | -- | -- | --
1 | [Algorithmic Racism & Environmental Data Justice](https://github.com/datatogether/reading_datatogether/issues/72) | How do choices in technology design and implementation reflect and impact broader social structures?  Let's explore, starting with readings from environmental data justice and studies of algorithmic racism.  | Lourdes, Rico
2 | [(Content) Moderation (and Consent)](https://github.com/datatogether/reading_datatogether/issues/73) | This topic covers factors that impact the content that we see. How do platforms balance freedom of expression versus consent to avoid offensive content, navigate algorithmic versus human moderation and curation, or incentivize different types of interaction? What are downstream effects of these choices? | Kelsey, **?**
3 | [Data Monopolies](https://github.com/datatogether/reading_datatogether/issues/75) | Most of our data and information is controlled by a handful of companies. How did this come to be, what are examples of responsible and irresponsible holding of this power, and how do we imagine we might slip the trap of data monopolies?  | J Victor, **?**
4 | [Trust (Cryptographic and Human)](https://github.com/datatogether/reading_datatogether/issues/74) | New technologies attempt to free us from (data) monopolized spaces, but does cryptographic trust truly map onto or enable better human-to-human (or human-to-company or human-to-technology) trust? | B5, Dawn
5 | [Private Data & Policies](https://github.com/datatogether/reading_datatogether/issues/76) | How have particular implementations of data privacy policies impacted humans, economics, and legal systems? What are appropriate expectations around data privacy, and who should inform, create, or enforce policies? | J Victor, **?**
6 | [Polity](https://github.com/datatogether/reading_datatogether/issues/77) | Who are the groups of people to whom we are connected in systems of governance? To whom do we owe allegiance? |  Stefan, **?**

## To-do
* [ ] Finish assigning facilitators
* [ ] Decide on dates (or at least months)
* [ ] Pull together readme and issues for collection of readings

**Comment by Frijol** [comment]
I think this closes https://github.com/datatogether/reading_datatogether/issues/58

**Comment by titaniumbones** [comment]
I could help, anyone wnat me?

**Comment by b5** [comment]
Any interest in joining me on #74 - Trust Readings @titaniumbones? 😄
